//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoServiceInfracciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public int id_reg { get; set; }
        public Nullable<System.DateTime> fec_ult_registro { get; set; }
        public string usu_ult_reg { get; set; }
    }
}
