//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoServiceInfracciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Extraccion
    {
        public string id_extraccion { get; set; }
        public string id_mineral { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<int> id_unidad { get; set; }
    
        public virtual Extraccion Extraccion { get; set; }
        public virtual Mineral Mineral { get; set; }
        public virtual Unidad Unidad { get; set; }
    }
}
