//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoServiceInfracciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Yacimiento = new HashSet<Yacimiento>();
        }
    
        public string id_empleado { get; set; }
        public string nombre { get; set; }
        public string apellidopat { get; set; }
        public string apellidomat { get; set; }
        public string documento { get; set; }
        public Nullable<decimal> sueldo { get; set; }
        public Nullable<System.DateTime> fec_nac { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string foto { get; set; }
        public string id_ubigeo { get; set; }
        public int id_cargo { get; set; }
        public string est_emp { get; set; }
        public Nullable<System.DateTime> fec_reg { get; set; }
        public string usu_reg { get; set; }
        public Nullable<System.DateTime> fec_ult_mod { get; set; }
        public string usu_ult_mod { get; set; }
    
        public virtual Cargos Cargos { get; set; }
        public virtual Ubigeo Ubigeo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yacimiento> Yacimiento { get; set; }
    }
}
