//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoServiceInfracciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimiento
    {
        public string id_mantenimiento { get; set; }
        public string id_maquinaria { get; set; }
        public string tipo { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public string est_man { get; set; }
        public string comentario { get; set; }
        public Nullable<System.DateTime> fec_reg { get; set; }
        public string usu_reg { get; set; }
        public Nullable<System.DateTime> fec_ult_mod { get; set; }
        public string usu_ult_mod { get; set; }
    
        public virtual Maquinaria Maquinaria { get; set; }
    }
}
