//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoServiceInfracciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yacimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yacimiento()
        {
            this.Extraccion = new HashSet<Extraccion>();
            this.Maquinaria = new HashSet<Maquinaria>();
            this.Empleado = new HashSet<Empleado>();
        }
    
        public string id_yacimiento { get; set; }
        public string nombre { get; set; }
        public string id_ubigeo { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public string est_yac { get; set; }
        public Nullable<System.DateTime> fec_reg { get; set; }
        public string usu_reg { get; set; }
        public Nullable<System.DateTime> fec_ult_mod { get; set; }
        public string usu_ult_mod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Extraccion> Extraccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maquinaria> Maquinaria { get; set; }
        public virtual Ubigeo Ubigeo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleado { get; set; }
    }
}
