//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoServiceInfracciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yacimiento_aud
    {
        public string id_yacimiento { get; set; }
        public string nombre { get; set; }
        public string id_ubigeo { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public string est_yac { get; set; }
        public Nullable<System.DateTime> fec_reg { get; set; }
        public string usu_reg { get; set; }
        public Nullable<System.DateTime> fec_ult_mod { get; set; }
        public string usu_ult_mod { get; set; }
        public string accion { get; set; }
        public Nullable<System.DateTime> fechaAccion { get; set; }
    }
}
